//! The emoji sigil offers, and a picture of each.
//!
//! egui draws text from monochrome fonts only, and the emoji font it bundles
//! is a 2014 subset of Noto — 887 glyphs, none of them yellow and one of the
//! old picker's six (🧡) not among them, drawn as a box. So an emoji here is
//! not a character to be found in a font: it is a **picture**, Twemoji's SVG,
//! looked up by the string that goes over the wire. The string is still what
//! is sent and stored — SIP-19's reaction carries the emoji itself, up to
//! `MAX_EMOJI` bytes — so nothing on the exchange knows this table exists.
//!
//! Generated by `scripts/emoji-assets` from Unicode's `emoji-test.txt` and
//! the Twemoji tree, both committed as outputs so a build needs no network.
//! No skin tones in this version: they would multiply the people group by
//! six and want a tone chooser the picker does not have.
//!
//! Twemoji graphics are CC-BY 4.0 — `LICENSE-TWEMOJI` beside this crate, and
//! the credit in the README.

use std::sync::OnceLock;

mod table;

pub use table::EMOJI;

/// One emoji: what is sent, what it is called, where it sits, and where its
/// picture is in the pack.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Emoji {
    /// The emoji itself — fully qualified, with its variation selectors, as
    /// Unicode writes it. **This is the string that goes over the wire.**
    pub chars: &'static str,
    /// Unicode's name, lowercase: "grinning face".
    pub name: &'static str,
    pub group: Group,
    offset: u32,
    len: u32,
}

impl Emoji {
    /// The SVG, as Twemoji drew it.
    ///
    /// The pack is inflated once, on the first call, into a buffer that is
    /// then leaked: a few megabytes, deliberately, so every picture is a
    /// `&'static [u8]` and the image loader is handed bytes it never has to
    /// copy.
    pub fn svg(&self) -> &'static [u8] {
        let all = unpacked();
        &all[self.offset as usize..(self.offset + self.len) as usize]
    }

    /// A name for the picture in egui's image cache: one per emoji, stable
    /// across frames, and not the emoji itself — a URI wants ASCII.
    pub fn uri(&self) -> String {
        let mut s = String::from("bytes://emoji/");
        for (i, c) in self.chars.chars().enumerate() {
            if i > 0 {
                s.push('-');
            }
            s.push_str(&format!("{:x}", c as u32));
        }
        s.push_str(".svg");
        s
    }
}

/// Unicode's nine groups, in Unicode's order — the picker's sections.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Group {
    Smileys,
    People,
    Nature,
    Food,
    Travel,
    Activities,
    Objects,
    Symbols,
    Flags,
}

impl Group {
    pub const ALL: [Group; 9] = [
        Group::Smileys,
        Group::People,
        Group::Nature,
        Group::Food,
        Group::Travel,
        Group::Activities,
        Group::Objects,
        Group::Symbols,
        Group::Flags,
    ];

    /// The section heading.
    pub fn label(self) -> &'static str {
        match self {
            Group::Smileys => "Smileys & emotion",
            Group::People => "People & body",
            Group::Nature => "Animals & nature",
            Group::Food => "Food & drink",
            Group::Travel => "Travel & places",
            Group::Activities => "Activities",
            Group::Objects => "Objects",
            Group::Symbols => "Symbols",
            Group::Flags => "Flags",
        }
    }

    /// The emoji in this group, in Unicode's order.
    pub fn emoji(self) -> impl Iterator<Item = &'static Emoji> {
        EMOJI.iter().filter(move |e| e.group == self)
    }
}

/// The five on the strip that hangs off every message.
///
/// The most-sent yellow emoji, in the order Unicode's frequency data puts
/// them. A constant, not a preference: the strip is the same on every
/// message and every machine so the hand learns where things are. What the
/// *person* sends most is the picker's "Frequently used" row, and that is
/// theirs.
pub const QUICK: [&str; 5] = [
    "\u{1f602}", // face with tears of joy
    "\u{1f923}", // rolling on the floor laughing
    "\u{1f62d}", // loudly crying face
    "\u{1f64f}", // folded hands
    "\u{1f618}", // face blowing a kiss
];

/// The entry for a string, if it is one of ours — exactly as sent, variation
/// selectors and all.
pub fn find(chars: &str) -> Option<&'static Emoji> {
    table::BY_CHARS
        .binary_search_by(|&i| EMOJI[i as usize].chars.as_bytes().cmp(chars.as_bytes()))
        .ok()
        .map(|at| &EMOJI[table::BY_CHARS[at] as usize])
}

/// Every emoji whose name contains the words, case-insensitively, in
/// Unicode's order. Empty words match everything.
pub fn search(query: &str) -> impl Iterator<Item = &'static Emoji> {
    let words: Vec<String> = query.split_whitespace().map(|w| w.to_lowercase()).collect();
    EMOJI
        .iter()
        .filter(move |e| words.iter().all(|w| e.name.contains(w.as_str())))
}

static PACK: &[u8] = include_bytes!("../assets/emoji.pack");

fn unpacked() -> &'static [u8] {
    static ALL: OnceLock<&'static [u8]> = OnceLock::new();
    ALL.get_or_init(|| {
        use std::io::Read as _;
        let mut out = Vec::with_capacity(table::UNPACKED);
        flate2::read::ZlibDecoder::new(PACK)
            .read_to_end(&mut out)
            .expect("the emoji pack is generated and committed; it inflates");
        assert_eq!(
            out.len(),
            table::UNPACKED,
            "the pack and the table disagree"
        );
        Box::leak(out.into_boxed_slice())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_full_and_every_entry_is_found_by_its_own_string() {
        assert!(EMOJI.len() > 1500, "{} emoji", EMOJI.len());
        for e in EMOJI {
            assert_eq!(find(e.chars), Some(e), "{}", e.name);
        }
    }

    #[test]
    fn a_string_that_is_not_an_emoji_is_not_found() {
        assert_eq!(find(""), None);
        assert_eq!(find("a"), None);
        // The unqualified form of one that is in the table qualified: what
        // some keyboards type. It is a different string on the wire, and
        // the table does not pretend otherwise.
        assert!(find("\u{2764}\u{fe0f}").is_some());
        assert_eq!(find("\u{2764}"), None);
    }

    #[test]
    fn every_picture_is_an_svg_and_fits_the_wire() {
        // sqex-proto::message::MAX_EMOJI, which this crate does not depend on.
        const MAX_EMOJI: usize = 32;
        for e in EMOJI {
            assert!(
                e.svg().trim_ascii_start().starts_with(b"<svg"),
                "{}",
                e.name
            );
            assert!(
                e.chars.len() <= MAX_EMOJI,
                "{} is {} bytes",
                e.name,
                e.chars.len()
            );
        }
    }

    #[test]
    fn the_quick_five_are_all_in_the_table() {
        for q in QUICK {
            assert!(find(q).is_some(), "{q:?}");
        }
    }

    #[test]
    fn every_group_has_members_in_unicode_order() {
        let mut seen = 0;
        for g in Group::ALL {
            let n = g.emoji().count();
            assert!(n > 0, "{}", g.label());
            seen += n;
        }
        assert_eq!(seen, EMOJI.len());
        // The groups are contiguous runs, as emoji-test.txt lists them.
        let groups: Vec<Group> = EMOJI.iter().map(|e| e.group).collect();
        let mut runs = groups.clone();
        runs.dedup();
        assert_eq!(runs, Group::ALL.to_vec());
    }

    #[test]
    fn search_is_by_every_word_of_the_name() {
        let cats: Vec<&str> = search("grinning cat").map(|e| e.name).collect();
        assert!(cats.contains(&"grinning cat"), "{cats:?}");
        assert!(cats.contains(&"grinning cat with smiling eyes"), "{cats:?}");
        assert!(!cats.contains(&"cat"), "{cats:?}");
        assert!(search("cat").any(|e| e.name == "cat"));
        assert!(search("Grinning").any(|e| e.chars == "\u{1f600}"));
        assert_eq!(search("").count(), EMOJI.len());
        assert_eq!(search("zzzz-not-a-name").count(), 0);
    }

    #[test]
    fn a_uri_is_ascii_and_one_per_emoji() {
        let mut uris: Vec<String> = EMOJI.iter().map(|e| e.uri()).collect();
        assert!(uris.iter().all(|u| u.is_ascii()));
        uris.sort();
        uris.dedup();
        assert_eq!(uris.len(), EMOJI.len());
        assert_eq!(find("\u{1f600}").unwrap().uri(), "bytes://emoji/1f600.svg");
    }
}
